### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by mpainenz** [robshakir/pyangbind#58]
Hi Rob,

I've recently been trying to import a new Yang Model. I'm not sure if this problem I'm having is a result of that, or a new issue as part of the latest pyangbind codebase.

Anyhow, I'm getting the following error:

```
Traceback (most recent call last):
  File "C:/Projects/git/genband-oneems-service/src/main.py", line 24, in <module>
    test = yangtypes.YANGDynClass(base=yangtypes.RestrictedClassType(base_type=yangtypes.RestrictedClassType(base_type=int, restriction_dict={'range': ['0..4294967295']}, int_size=32), restriction_dict={'range': [u'0..4294967295']}), default=yangtypes.RestrictedClassType(base_type=int, restriction_dict={'range': ['0..4294967295']}, int_size=32)(0), is_leaf=True, yang_name="region-id", register_paths=True, namespace='http://genband.com/acs', defining_module='acs', yang_type='uint32', is_config=True)
  File "C:\Projects\git\genband-oneems-service\pyangbind\lib\yangtypes.py", line 345, in RestrictedClassType
    return type(RestrictedClass(*args, **kwargs))
  File "C:\Projects\git\genband-oneems-service\pyangbind\lib\yangtypes.py", line 271, in __new__
    ranges.append(build_length_range_tuples(range_spec))
  File "C:\Projects\git\genband-oneems-service\pyangbind\lib\yangtypes.py", line 190, in build_length_range_tuples
    high = base_type(high) if not high == "max" else None
  File "C:\Projects\git\genband-oneems-service\pyangbind\lib\yangtypes.py", line 320, in __new__
    obj = base_type.__new__(self, *args, **kwargs)
OverflowError: Python int too large to convert to C long
```

When attempting to run the following:

```
test = yangtypes.YANGDynClass(base=yangtypes.RestrictedClassType(base_type=yangtypes.RestrictedClassType(base_type=int, restriction_dict={'range': ['0..4294967295']}, int_size=32), restriction_dict={'range': [u'0..4294967295']}), default=yangtypes.RestrictedClassType(base_type=int, restriction_dict={'range': ['0..4294967295']}, int_size=32)(0), is_leaf=True, yang_name="region-id", register_paths=True, namespace='http://genband.com/acs', defining_module='acs', yang_type='uint32', is_config=True)
```

As you can see, I've tried to isolate the issue a little bit, but in actual practice my code is running something like:

```
            acs = yang_acs.acs()
            route_name = "000TestK_%s" % sql_call_route.CR_NAME
            cr = acs.call_routing.route.add(route_name)
```

That in turn is instantiating the bindings object which runs this line in my bindings file:

```
self.__region_id = YANGDynClass(base=RestrictedClassType(base_type=RestrictedClassType(base_type=int, restriction_dict={'range': ['0..4294967295']}, int_size=32), restriction_dict={'range': [u'0..4294967295']}), default=RestrictedClassType(base_type=int, restriction_dict={'range': ['0..4294967295']}, int_size=32)(0), is_leaf=True, yang_name="region-id", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://genband.com/acs', defining_module='acs', yang_type='uint32', is_config=True)
```

The yang for the region_id is as follows:
```
      leaf region-id {
        // add description from attribute, name=regionId
        description "An identifier to logically group a set of calling routes in a region; the Region ID is only used in percentage based routing; Default=0.";
        // match attribute mode=type: name=regionId type=long
        type uint32 {
          // match constraint type=range: # values=1
          range "0..4294967295";
        }
        default "0";
      } // leaf region-id
```

Anyway, the range seems valid for a 32bit unsigned integer. I'm not really sure what the point is in providing a range when that range is the full capacity of the data type.

Any ideas?

Cheers,
Mark

**Comment by robshakir** [comment]
Hi Mark,

What are you setting the value to please, and which code are you running - I assume the latest from this repo, rather than the latest from PyPI?

This test passes using the inbuilt test framework:

```python
  for v in  [(0, True), (10, True), (2**32-1, True), (2**64, False),
              (2**32, False)]:
    val_set = False
    try:
      u.issue_fixes.region_id = v[0]
      val_set = True
    except ValueError:
      pass
    assert v[1] is val_set, "Value of region_id incorrectly set %s (%s != %s" \
      % (v[0], val_set, v[1])
```

Thanks,
r.

**Comment by robshakir** [comment]
The issue is likely to be related to the work to replace numpy with use of inbuilt restricted types to reduce PyangBind's weight.

**Comment by mpainenz** [comment]
Hi Rob,

> What are you setting the value to?

I'm just instantiating the object at the point of failure, as per my example

> I assume the latest from this repo, rather than the latest from PyPI

Yes, this is correct, I'm using the latest source from the master branch. I have tried pulling the master branch again just now, and I still get this error.

**Comment by mpainenz** [comment]
Here's a more specific example:

```
module test {

  namespace "http://test.com/test";
  prefix "test";

  container test {
    leaf region-id {
      description "An identifier to logically group a set of calling routes in a region; the Region ID is only used in percentage based routing; Default=0.";
      type uint32 {
        range "0..4294967295";
      }
      default "0";
    }
  }
}
```

Here is a class bindings file from that example yang -> [yang_acs.zip](https://github.com/robshakir/pyangbind/files/212002/yang_acs.zip)


The following code will fail:

```
from yang_acs import test
test_obj = test()
```


```
TypeError: couldn't generate dynamic type -> <type 'exceptions.OverflowError'> -> Python int too large to convert to C long
```

**Comment by mpainenz** [comment]
Commenting out the following line of Yang prevents the error from occuring:

> range "0..4294967295";

**Comment by robshakir** [comment]
Hi Mark,

In https://github.com/robshakir/pyangbind/commit/51b4fac68a614f754699c84e184e4476f0f5fedb I added a specific test using the YANG that you provided, the build seems to succeed (see https://travis-ci.org/robshakir/pyangbind/builds/121709458).

There were commits that I did not squash when I merged to master that had slightly broken behaviour on them. I wonder whether you're running one of those?

Either way, I can't reproduce this issue unfortunately.

r.

**Comment by mpainenz** [comment]
OK Rob,

I've tun the uint tests unit, and I get the same error.

I guess there is something specific to my Python instance which is causing issues. I'll keep playing around at this end, and see what I can find.

**Comment by mpainenz** [comment]
This might be related to using a 32bit installation of Python, or perhaps a Windows related thing.

It's quite possibly not a Numpy issues, I've recently migrated to a new YANG model, it's quite possible that this issue predated any Numpy related changes.

**Comment by mpainenz** [comment]
Installing a 64bit Python instance does not resolve this

**Comment by mpainenz** [comment]
```
  # u.issue_fixes.region_id = 4294967294 #Causes exception

  u.issue_fixes.region_id = 2147483647 #signed int32 works
  u.issue_fixes.region_id = 2147483648 #doesn't work
```

Still not sure exactly where in the code base this exception originates, however just confirming that the value works until the limit of an uint32 is passed

**Comment by mpainenz** [comment]
Temporary workaround:

Changing the following lines from plugin.py

From 

```
    'uint32': {
        "native_type": "RestrictedClassType(base_type=int, restriction_dict={'range': ['0..4294967295']}, int_size=32)",
        "base_type": True,
        "pytype": RestrictedClassType(base_type=int, restriction_dict={'range': ['0..4294967295']}, int_size=32)
    },
```

to

```
    'uint32': {
        "native_type": "RestrictedClassType(base_type=long, restriction_dict={'range': ['0..4294967295']}, int_size=32)",
        "base_type": True,
        "pytype": RestrictedClassType(base_type=int, restriction_dict={'range': ['0..4294967295']}, int_size=32)
    },
```


Changing the base type to 'long' works, but I think this would break under Python 3 which merges int and long (I think).

I'm still not sure why this works on other OS/Interpreter combinations

**Comment by robshakir** [comment]
Hi Mark,

Interesting - thanks for finding this out.

I can confirm that the test passes when I run this on both Linux (Debian) and OS X. There is already precedent for using `long` since this is how `(u)?int64` values are also stored - this will need be fixed for Python 3 compatibility anyway.

I've switched to using `long` for both the 32-bit integer types based on this feedback - I'll commit this fix in a moment, but as far as I can see, it should work fine.

It'd be interesting to see, from your system, the output of:

```python
#!/usr/bin/env python

import sys

print sys.maxint
```

On my OS X and Linux hosts, this is:

```
>>> import sys
>>> print sys.maxint
9223372036854775807
```

I'm imagining it is quite a lot smaller in your Python - the [docs](https://docs.python.org/2/library/sys.html#sys.maxint) indicate that it could be as small as 2**32-1, which might explain this issue.

Thanks,
r.

**Comment by mpainenz** [comment]
Yes, this is a bit bizarre, running the following:


```
  print platform.python_version()
  print sys.maxint
  print sys.maxsize
  is_64bits = sys.maxsize > 2**32
  print is_64bits
```

 Against my 64bit Python interpreter I get the following:

```
2.7.11
2147483647
9223372036854775807
True
```

Against my 32Bit Python interpreter I get:

```
2.7.11
2147483647
2147483647
False
```

**Comment by mpainenz** [comment]
Thanks for the Commit, I've now been able to import this troublesome model. So far it's working. 

Cheers!
Mark
